/**
 * Core domain types.
 *
 * PRIVACY NOTE: nothing in this file (or anywhere in the repo) contains data
 * VALUES. The only data-derived strings allowed are column *header names*
 * (see schema.ts `defaultHeaders`). All values are discovered at runtime from
 * the file the user loads in their own browser.
 */

/** The 50 logical roles the dashboard understands (mapped to headers at runtime). */
export type LogicalRole =
  // identity & period
  | 'requisitionId'
  | 'positionTitle'
  | 'calendarYear'
  // demand
  | 'demandType'
  | 'budgetFlag'
  | 'replacementOf'
  // org dimensions
  | 'businessUnit'
  | 'function'
  | 'haziraFlag'
  | 'location'
  | 'level'
  | 'hrHead'
  | 'hrbp'
  | 'recruiter'
  | 'rpoLead'
  // funnel status
  | 'stage'
  | 'stageGroup'
  | 'subStage'
  | 'jdFlag'
  | 'qualification'
  // ageing
  | 'ageingDays'
  | 'ageingBucket'
  | 'ageingReason'
  // funnel date spine
  | 'reqReceivedDate'
  | 'intakeDate'
  | 'selectionDate'
  | 'documentationDate'
  | 'remunerationDate'
  | 'draftOfferSentDate'
  | 'draftOfferApprovedDate'
  | 'sentForApprovalDate'
  | 'offerApprovalDate'
  | 'offerSentDate'
  | 'offerAcceptedDate'
  | 'joiningDate'
  // post-offer / onboarding
  | 'medicalInitiationDate'
  | 'medicalCompletionDate'
  | 'bgvInitiationDate'
  | 'bgvCompletionDate'
  | 'kcheckNo'
  | 'employeeNo'
  // diversity
  | 'gender'
  // source
  | 'source'
  // TBO
  | 'tboAgeingDays'
  | 'tboBucket'
  | 'tboAgeingReason'
  | 'nextFollowUp'
  | 'actionables'
  // drops
  | 'dropList'
  // notes
  | 'taRemark';

export type FieldKind = 'id' | 'text' | 'category' | 'boolean' | 'date' | 'number';

export type RoleGroup =
  | 'identity'
  | 'demand'
  | 'org'
  | 'funnel'
  | 'ageing'
  | 'dates'
  | 'postoffer'
  | 'diversity'
  | 'source'
  | 'tbo'
  | 'drops'
  | 'notes';

/** Generic canonicalisation rule-set applied to a category/boolean field. */
export type CanonicalKind = 'demandType' | 'gender' | 'source' | 'budget' | 'hazira' | 'yesno';

export interface RoleDef {
  key: LogicalRole;
  /** Neutral UI label (e.g. the personal-name header "Alifiya's Remark" -> "TA Remark"). */
  label: string;
  kind: FieldKind;
  /** PII / free-text people field -> masked by default in shared & export views. */
  sensitive: boolean;
  group: RoleGroup;
  /** Candidate header names for auto-mapping. HEADER NAMES ONLY — never values. */
  defaultHeaders: string[];
  /** If present, the generic canonical bucket rules used to normalise this field. */
  canonical?: CanonicalKind;
  description?: string;
}

// ───────────────────────── Parsing ─────────────────────────

export type RawCell = string | number | boolean | null;
export type RawRow = RawCell[]; // aligned to `headers` by index

export interface ParsedTable {
  headers: string[];
  rows: RawRow[];
  sheetName: string;
  /** Kept in-memory only; never transmitted. Cleared on "Clear all data". */
  fileName: string;
  /** true when generated by the in-code demo generator (badged in UI). */
  isDemo?: boolean;
}

/** Per-column profile used by the Mapping Screen (low-cardinality distinct values). */
export interface ColumnProfile {
  header: string;
  index: number;
  filled: number;
  total: number;
  distinct: number;
  /** distinct raw values, ONLY when low-cardinality; capped. Empty for high-cardinality. */
  sampleValues: string[];
  /** rough shape inference for auto-mapping hints. */
  inferredKind: FieldKind;
  dateLikeShare: number;
  numericShare: number;
}

export interface TableProfile {
  headers: string[];
  rowCount: number;
  sheetName: string;
  fileName: string;
  isDemo: boolean;
  columns: ColumnProfile[];
}

// ───────────────────────── Mapping config (persisted locally) ─────────────────────────

export interface MappingConfig {
  version: number;
  /** logical role -> chosen header (null = explicitly unmapped). */
  roleToHeader: Partial<Record<LogicalRole, string | null>>;
  /** role -> { normalisedRawToken -> canonicalValue } user overrides. */
  valueOverrides: Partial<Record<LogicalRole, Record<string, string>>>;
  /** user-confirmed ordered canonical funnel built from discovered `stage` values. */
  stageOrder?: string[];
  updatedAt: number;
}

// ───────────────────────── Normalised dataset ─────────────────────────

export interface NormalizedRow {
  /** original row index (1-based data row) for private drill-down. */
  i: number;
  reqId: string | null;
  /** composite key used for de-duplication. */
  dedupKey: string;
  cat: Partial<Record<LogicalRole, string | null>>; // canonical category / id / text
  date: Partial<Record<LogicalRole, number | null>>; // epoch ms
  num: Partial<Record<LogicalRole, number | null>>;
  bool: Partial<Record<LogicalRole, boolean | null>>;
  // derived status
  isJoined: boolean;
  isOpen: boolean;
  isOnHold: boolean;
  isTBO: boolean;
  wasDropped: boolean;
  /** sanitized drop-reason phrase (name-stripped) for analysis without exposing identity. */
  dropReason: string | null;
}

export interface DedupSummary {
  inputRows: number;
  outputRows: number;
  duplicateGroups: number;
  rowsDropped: number;
  blankIdRows: number;
  /** ids that repeat suspiciously often (likely placeholders, not real dups). */
  highFrequencyIds: number;
}

// ───────────────────────── Data-quality report ─────────────────────────

export interface FieldCompleteness {
  role: LogicalRole;
  label: string;
  header: string | null;
  kind: FieldKind;
  filled: number;
  total: number;
  pct: number;
  broken: boolean;
}

export interface DateHealth {
  role: LogicalRole;
  label: string;
  header: string | null;
  valid: number;
  missing: number;
  invalid: number;
}

export interface VocabViolation {
  role: LogicalRole;
  label: string;
  header: string | null;
  matched: number;
  total: number;
  unmatchedTokens: { token: string; count: number }[];
}

export interface BrokenColumn {
  role: LogicalRole;
  label: string;
  header: string | null;
  filledPct: number;
  reason: string;
}

export interface ConsistencyIssue {
  key: string;
  label: string;
  count: number;
  /** sample of offending original row indices (capped) for drill-down. */
  rowIndices: number[];
}

export interface DataQualityReport {
  rows: number;
  completeness: FieldCompleteness[];
  dateHealth: DateHealth[];
  vocab: VocabViolation[];
  broken: BrokenColumn[];
  consistency: ConsistencyIssue[];
  score: {
    overall: number;
    completeness: number;
    validity: number;
    consistency: number;
  };
}

export interface NormalizeResult {
  rows: NormalizedRow[];
  dq: DataQualityReport;
  dedup: DedupSummary;
}
